# -*- coding: utf-8 -*-

"""
dimer_builder_step
A SEAMM plug-in for Dimer Builder
"""

# Bring up the classes so that they appear to be directly in
# the dimer_builder_step package.
# The Substep base class is exposed at the package level so that substep
# modules (generated by the substep cookiecutter) can subclass it as
# `dimer_builder_step.Substep`.
from .dimer_builder_substep import Substep  # noqa: F401

from .dimer_builder import DimerBuilder  # noqa: F401, E501
from .dimer_builder_step import DimerBuilderStep  # noqa: F401, E501
from .tk_dimer_builder import TkDimerBuilder  # noqa: F401, E501

from .metadata import metadata  # noqa: F401

# Handle versioneer
from ._version import get_versions

__author__ = "Paul Saxe"
__email__ = "psaxe@molssi.org"
versions = get_versions()
__version__ = versions["version"]
__git_revision__ = versions["full-revisionid"]
del get_versions, versions
